# Generated by Django 5.0.6 on 2026-09-13 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_marketsignal_current_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.JSONField(blank=True, default=list, help_text='List of market symbols starred by user')),
                ('email_alerts_enabled', models.BooleanField(default=True, help_text='Whether to dispatch trade signal alerts to user email')),
                ('alert_min_quality', models.IntegerField(default=70, help_text='Minimum setup quality score (0-100%) to trigger an email alert')),
                ('alert_directions', models.CharField(choices=[('all', 'All Directions'), ('Buy', 'Buy Signals Only'), ('Sell', 'Sell Signals Only')], default='all', max_length=16)),
                ('alert_favorites_only', models.BooleanField(default=False, help_text='If True, only send alerts for symbols in favorites list')),
                ('alert_timeframe', models.CharField(choices=[('all', 'All Timeframes'), ('1H', '1 Hour (1H)'), ('4H', '4 Hours (4H)'), ('1D', '1 Day (1D)')], default='all', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
