# Generated by Django 5.0.6 on 2026-09-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsignal',
            name='market_regime',
            field=models.CharField(blank=True, default='', help_text='Market regime detected when signal was generated', max_length=16),
        ),
        migrations.AddField(
            model_name='marketsignal',
            name='strategy_mode',
            field=models.CharField(blank=True, default='default', help_text='Analysis mode used to generate this signal', max_length=16),
        ),
    ]
